### PR TITLE
sync repository

### PR DESCRIPTION
**Pull request by Apoorva-Datir**
I've been assigned to issue  LCM Function #19 
output screenshot:[
image
](url)

### CODE REVIEW

**Comment by SuyashSonawane** [comment]
Hi @Apoorva-Datir  can you please resolve these conflicts and push again?

**Comment by Apoorva-Datir** [comment]
I've done it.Please  check it @SuyashSonawane

**Comment by Apoorva-Datir** [comment]
I am sorry , there is some error ,I'll resolve it.

**Comment by Apoorva-Datir** [comment]
please review it @SuyashSonawane

**Review by tejasmorkar — APPROVED** [review]

**Pull request merged**
