### PR TITLE
Add functions for area and perimeter

### PR DESCRIPTION
**Pull request by varunpusarla**
**I added the functions for finding areas and perimeters**

image

### CODE REVIEW

**Comment by varunpusarla** [comment]
Guys can you review this and merge @tejasmorkar @SuyashSonawane

**Review by SuyashSonawane — CHANGES_REQUESTED** [review]
@varunpusarla nice work 
can you merge all area functions and perimeter functions in a single file named `area.py` and then you can create an options menu to select the respective shape, same with the perimeter

Because if we create new files for just one one functions then it would be difficult to manage

After you do your changes please message before creating a pull request

**Comment by varunpusarla** [comment]
I made the changes as you proposed and pushed them. @SuyashSonawane. Do review it again.

image

**Review by SuyashSonawane — APPROVED** [review]
Awesome 🥳

**Pull request merged**
